name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  tests:
    name: "Python ${{ matrix.python-version }}"
    runs-on: ${{ matrix.os }}
    env:
      USING_COVERAGE: '3.6,3.8'

    strategy:
      matrix:
        os: [macos-latest]
        python-version: ["3.8","pypy-3.8"]

    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v4"
        with:
          python-version: "${{ matrix.python-version }}"
          architecture: x64

      - name: "Run facebook scraper command"
        run: |
          chmod +x src/read_lines.sh
          src/read_lines.sh
          
#       - name: "Commit and push if it changed"
#         run: |
#           git config user.name "Automated"
#           git config user.email "actions@users.noreply.github.com"
#           git add -A
#           timestamp=$(date -u)
#           git commit -m "Latest data: ${timestamp}" || exit 0
#           git push -f origin main

